# See https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main
  repo: danielmoessner/avphd.de

# See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

# See https://www.netlifycms.org/docs/configuration-options/#locale
locale: de

# See https://www.netlifycms.org/docs/configuration-options/#display-url
display_url: dobbrunz.netlify.app

# See https://www.netlifycms.org/docs/configuration-options/#site-url
site_url: dobbrunz.netlify.de

# See https://www.netlifycms.org/docs/configuration-options/#media-folder
media_folder: /content/media

# See https://www.netlifycms.org/docs/configuration-options/#public-folder
public_folder: ../media

# See https://www.netlifycms.org/docs/collection-types/
collections:
  - name: page
    label: Seiten
    label_singular: Seite
    delete: false
    editor:
      preview: false
    files:
      - file: content/pages/home.yml
        label: Startseite
        name: home
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: home }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }

  - name: company
    label: Unternehmen
    label_singular: Unternehmen
    editor:
      preview: true
    folder: content/companies
    slug: '{{fields.name}}'
    create: true
    extension: yml
    # preview_path: wildtiere/{{fields.slug}}
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: company }
      - { label: Name, name: name, widget: string }
      - { label: Bild, name: image, widget: image }
      - { label: Beschreibung, name: description, widget: text }

  - name: project
    label: Projekte
    label_singular: Projekt
    editor:
      preview: true
    folder: content/projects
    slug: '{{fields.name}}'
    create: true
    extension: yml
    # preview_path: wildtiere/{{fields.slug}}
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: project }
      - { label: Name, name: name, widget: string }
      - { label: Bild, name: image, widget: image }
      - { label: Beschreibung, name: description, widget: text }

  - name: 'setting'
    label: Einstellungen
    label_singular: Einstellung
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: Global
        name: 'global-settings'
        preview: false
        fields:
          - {
              label: Sammlung,
              name: collection,
              widget: hidden,
              default: setting
            }
          - { label: Slug, name: slug, widget: hidden, default: global }
          - {
              label: URL der Seite,
              name: siteUrl,
              widget: string,
              required: false
            }
          - { label: Favicon, name: favicon, widget: image }
